task names:
    Basic concepts and history of cryptography:
        - Atbash
        - Scytale
        - Polybius Square
        - Caesar
        - Cardan grille
        - Richelieu
    Classical symmetric cryptosystems:
        - name1
        - name2
        - name3
    Modern symmetric cryptosyste:
        - name4
        - name5

task id:
    default: 0
    Atbash: 1
    Scytale: 2
    Polybius Square: 3
    Caesar: 4
    Cardan grille: 5
    Richelieu: 6
