app name: Crypto methods

task names:
    Symmetric encryption:
        Basic concepts and history of cryptography:
            - Atbash
            - Scytale
            - Polybius Square
            - Caesar
            - Cardan grille
            - Richelieu

        Classical symmetric cryptosystems:
            - Alberti disc
            - Gronsfeld
            - Vigenere
            - Playfair
            - Hill
            - Vernam

    Asymmetric encryption:


task id:
    Default: 0

    Atbash: 1
    Scytale: 2
    Polybius Square: 3
    Caesar: 4
    Cardan grille: 5
    Richelieu: 6

    Alberti disc: 7
    Gronsfeld: 8
    Vigenere: 9
    Playfair: 10
    Hill: 11
    Vernam: 12

